### ISSUE TITLE
attached PDF is not working

### ISSUE THREAD

**Issue by alessandro-gi** [Future-House/paper-qa#119] opened 2023-05-22 14:43 UTC
[19515.pdf](https://github.com/whitead/paper-qa/files/11532114/19515.pdf)

The text of this PDF (italian legal case) for some reason is not extracted.
AI answer: 'The provided context describes a document written in a code or cipher, with no clear indication of its content or language....'

**Comment by jamesbraza** [comment] 2024-09-11 18:26
Hello @alessandro-gi, we have just released version 5, which basically rewrites everything and comes with step function improvements in performance.

Do you mind pulling in `paper-qa>=5` and retrying your query? Also, if it still doesn't work, can you post a minimal repro for us to take a look?

**Comment by maykcaldas** [comment] 2024-12-11 02:05
Hey @alessandro-gi , I tested it on the new version and `paper-qa` is able to parse it. 

Querying:
```
session = await docs.aquery(
    "Look at the document available and tell me what it is about?",
    settings=settings,
)
```

gives me the following answer:
`
(...)The document appears to be an official record or registration related to legal or administrative proceedings in Italy. It contains multiple registration numbers, including "Numero registro generale 18642/2018", "Numero sezionale 2373/2022", and "Numero di raccolta generale 19515/2022" (Numero1864 pages 10-11, Numero1864 pages 11-11). The document was published on June 16, 2022 (Numero1864 pages 14-14). (...)
`

I'm closing the issue. Please feel free to reopen it if the issue is not answered.

**Closed by maykcaldas** 2024-12-11 02:05 UTC
Labels: question
