### ISSUE TITLE
HuggingFace Demo Broken?

### ISSUE THREAD

**Issue by evanVerinomics** [Future-House/paper-qa#214] opened 2023-12-01 16:19 UTC
Space failed. Exit code: 1. Reason: Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import paperqa
  File "/home/user/.local/lib/python3.8/site-packages/paperqa/__init__.py", line 1, in <module>
    from .docs import Answer, Docs, PromptCollection, Doc, Text
  File "/home/user/.local/lib/python3.8/site-packages/paperqa/docs.py", line 35, in <module>
    class Docs(BaseModel, arbitrary_types_allowed=True, smart_union=True):
  File "/home/user/.local/lib/python3.8/site-packages/paperqa/docs.py", line 43, in Docs
    llm: Union[str, BaseLanguageModel] = ChatOpenAI(
  File "/home/user/.local/lib/python3.8/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
  
  I get the same error when I try to run this, This used to work and I've tried updating my openai api key but still get errors. 
  
  export OPENAI_API_KEY="sk-foo"

**Comment by kaiwen-wang** [comment] 2024-01-06 23:16
also having this issue

**Comment by jamesbraza** [comment] 2024-09-11 18:28
Closing as a duplicate of https://github.com/Future-House/paper-qa/issues/196

**Closed by jamesbraza** 2024-09-11 18:28 UTC
Labels: bug
