### ISSUE TITLE
aviary long_description

### ISSUE THREAD

**Issue by CrispStrobe** [Future-House/paper-qa#372] opened 2024-09-11 22:15 UTC
thanks for today's fascinating new release. i got a few errors on first try, after pip installing / upgrading a few things (pymupdf eg was missing), then stuck on 
AttributeError: 'Docstring' object has no attribute 'description'. Did you mean: 'long_description'?
which i q&d fixed by editing aviary/tools/base.py lines 315,321,364, changing docstring.description indeed to docstring.long_description, which resolved that. btw, you only provide fhaviary via pypi but not as a github repo (anymore)?

**Comment by jamesbraza** [comment] 2024-09-11 22:39
Can you share your full stack trace? What you have is not quite enough for us to root cause.

And `fhaviary` repo will be made un-private soon, we are going to do that in a few weeks

**Comment by CrispStrobe** [comment] 2024-09-12 07:40
Thanks. Afraid i have not a pip list output from the time of first install. but i know that then i had pydantic 2.6.4 & pydantic-settings 2.2.1 & ran into
ImportError: cannot import name 'CliSettingsSource' from 'pydantic_settings'
at paperqa/agents/__init__.py", line 8
& same after updating some packages, including pydantic 2.9.1, but only after updating to pydantic-settings 2.5.2, that went away.
next i ran into ModuleNotFoundError: No module named 'pymupdf'
from paperqa/utils.py", line 23
easily solved of course per pip install. but the
AttributeError: 'Docstring' object has no attribute 'description'. Did you mean: 'long_description'?
from aviary/tools/base.py i was only able to get rid of by changig those lines.

**Comment by jamesbraza** [comment] 2024-09-12 16:20
@CrispStrobe can you share me what version of `docstring_parser` you are using? Also, are you able to share the code you ran that led you to this error?

**Comment by jamesbraza** [comment] 2024-09-12 17:29
Turns out due to https://github.com/rr-/docstring_parser/commit/a12cca9b80fb2404f7625a3ad052b2b7d3a130d4 that aviary depends upon `docstring_parser>=0.16` lol

So if you upgrade `docstring_parser` it will work. Thanks for this, we are pinning it on our side shortly

**Comment by jamesbraza** [comment] 2024-09-12 18:04
Okay @CrispStrobe the pinning of `docstring_parser>=0.16` is finished and released: https://pypi.org/project/fhaviary/0.6.1/

Going to close this out, feel free to follow up if you're still stuck.

Please just run `pip install --upgrade fhaviary` or reinstall `paper-qa` dependencies with `--upgrade`

**Closed by jamesbraza** 2024-09-12 18:04 UTC
Labels: needs information

**Comment by CrispStrobe** [comment] 2024-09-12 19:00
perfect, works - and thanks for the swift solution!
